import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react';
import type { Category, CheatSheet, CheatSheetInput, CheatSheetStep, CheatSheetType, TemplateVariable } from '../types';
import { detectTemplateVariablesInContents, normalizeTags } from '../utils';
type Props={open:boolean;categories:Category[];item?:CheatSheet;onClose:()=>void;onSave:(input:CheatSheetInput)=>Promise<void>};
const emptyStep=(sortOrder:number):CheatSheetStep=>({sortOrder,title:'',description:'',content:''});
export function EditDialog({open,categories,item,onClose,onSave}:Props){
 const[categoryId,setCategoryId]=useState(0),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[type,setType]=useState<CheatSheetType>('single'),[content,setContent]=useState(''),[steps,setSteps]=useState<CheatSheetStep[]>([]),[tags,setTags]=useState(''),[variables,setVariables]=useState<TemplateVariable[]>([]),[saving,setSaving]=useState(false);
 const detectedNames=useMemo(()=>detectTemplateVariablesInContents(type==='single'?[content]:steps.map(s=>s.content)),[type,content,steps]);
 const detectedVariables=detectedNames.map((name,sortOrder)=>variables.find(v=>v.name===name)??{name,defaultValue:'',description:'',sortOrder});
 useEffect(()=>{if(open){setCategoryId(item?.categoryId??categories[0]?.id??0);setTitle(item?.title??'');setDescription(item?.description??'');setType(item?.type??'single');setContent(item?.content??'');setSteps(item?.steps.length?item.steps:[emptyStep(0)]);setTags(item?.tags.join(', ')??'');setVariables(item?.templateVariables??[]);}},[open,item,categories]);
 if(!open)return null;
 const updateStep=(index:number,changes:Partial<CheatSheetStep>)=>setSteps(current=>current.map((step,i)=>i===index?{...step,...changes}:step));
 const moveStep=(index:number,offset:number)=>setSteps(current=>{const next=[...current],target=index+offset;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next;});
 const updateVariable=(name:string,changes:Partial<TemplateVariable>)=>setVariables(current=>{const existing=current.find(v=>v.name===name)??{name,defaultValue:'',description:'',sortOrder:detectedNames.indexOf(name)};return[...current.filter(v=>v.name!==name),{...existing,...changes}];});
 async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);try{await onSave({id:item?.id,categoryId,title:title.trim(),description:description.trim(),type,content:type==='single'?content:'',steps:type==='command_set'?steps.map((s,i)=>({...s,sortOrder:i})):[],tags:normalizeTags(tags),templateVariables:detectedVariables});onClose();}finally{setSaving(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal command-editor-modal" onSubmit={submit}><h2>{item?'CheatSheetを編集':'新しいCheatSheet'}</h2>
  <label>カテゴリ<select value={categoryId} onChange={e=>setCategoryId(Number(e.target.value))} required>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>タイトル<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={120} autoFocus/></label><label>説明<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={2}/></label>
  <fieldset className="type-selector"><legend>種類</legend><label><input type="radio" checked={type==='single'} onChange={()=>setType('single')}/>Single Command</label><label><input type="radio" checked={type==='command_set'} onChange={()=>setType('command_set')}/>Command Set</label></fieldset>
  {type==='single'?<label>コマンド / 本文<textarea className="code-input" value={content} onChange={e=>setContent(e.target.value)} rows={8} required/></label>:<section className="steps-editor"><div className="steps-editor-heading"><h3>Steps</h3><button type="button" className="secondary" onClick={()=>setSteps(s=>[...s,emptyStep(s.length)])}><Plus size={14}/>Step追加</button></div>{steps.map((step,index)=><div className="step-editor" key={step.id??`new-${index}`}><div className="step-editor-title"><strong>Step {index+1}</strong><div><button type="button" className="icon-button" onClick={()=>moveStep(index,-1)} disabled={index===0} aria-label="上へ"><ArrowUp size={15}/></button><button type="button" className="icon-button" onClick={()=>moveStep(index,1)} disabled={index===steps.length-1} aria-label="下へ"><ArrowDown size={15}/></button><button type="button" className="danger-text" onClick={()=>setSteps(s=>s.filter((_,i)=>i!==index))} disabled={steps.length===1}><Trash2 size={14}/>削除</button></div></div><label>Stepタイトル<input value={step.title} onChange={e=>updateStep(index,{title:e.target.value})}/></label><label>Step説明<textarea value={step.description} onChange={e=>updateStep(index,{description:e.target.value})} rows={2}/></label><label>コマンド<textarea className="code-input" value={step.content} onChange={e=>updateStep(index,{content:e.target.value})} rows={5} required/></label></div>)}</section>}
  {detectedVariables.length?<section className="variable-editor"><h3>検出された変数</h3>{detectedVariables.map(v=><div className="variable-row" key={v.name}><strong>{v.name}</strong><label>デフォルト値<input value={v.defaultValue} onChange={e=>updateVariable(v.name,{defaultValue:e.target.value})}/></label><label>説明<input value={v.description} onChange={e=>updateVariable(v.name,{description:e.target.value})}/></label><label>表示順<input type="number" min="0" value={v.sortOrder} onChange={e=>updateVariable(v.name,{sortOrder:Number(e.target.value)})}/></label></div>)}<p className="secret-warning">パスワード・トークン等の秘密情報は保存しないでください。</p></section>:null}
  <label>タグ（カンマ区切り）<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="git, status"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>キャンセル</button><button className="primary" disabled={saving||!categories.length}>{saving?'保存中…':'保存'}</button></div></form></div>;
}
