use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use std::{fs, path::PathBuf, sync::Mutex};
use tauri::{Manager, State};

struct AppState(Mutex<Connection>);
#[derive(Serialize,Deserialize,Clone)] #[serde(rename_all="camelCase")] struct Category{id:i64,name:String,sort_order:i64,created_at:String}
#[derive(Serialize,Deserialize,Clone)] #[serde(rename_all="camelCase")] struct TemplateVariable{id:Option<i64>,name:String,default_value:String,description:String,sort_order:i64}
#[derive(Serialize,Deserialize,Clone)] #[serde(rename_all="camelCase")] struct CheatSheetStep{id:Option<i64>,cheatsheet_id:Option<i64>,sort_order:i64,title:String,description:String,content:String}
#[derive(Serialize,Deserialize,Clone)] #[serde(rename_all="camelCase")] struct CheatSheet{id:i64,category_id:i64,category_name:String,title:String,description:String,#[serde(rename="type")]sheet_type:String,content:String,steps:Vec<CheatSheetStep>,tags:Vec<String>,template_variables:Vec<TemplateVariable>,created_at:String,updated_at:String}
#[derive(Deserialize)] #[serde(rename_all="camelCase")] struct CheatSheetInput{id:Option<i64>,category_id:i64,title:String,description:String,#[serde(rename="type",default="default_sheet_type")]sheet_type:String,#[serde(default)]content:String,#[serde(default)]steps:Vec<CheatSheetStep>,tags:Vec<String>,#[serde(default)]template_variables:Vec<TemplateVariable>}
#[derive(Serialize,Deserialize)] #[serde(rename_all="camelCase")] struct BackupCategory{name:String,sort_order:i64}
#[derive(Serialize,Deserialize)] #[serde(rename_all="camelCase")] struct BackupItem{category:String,title:String,description:String,#[serde(rename="type",default="default_sheet_type")]sheet_type:String,#[serde(default)]content:String,tags:Vec<String>,#[serde(default)]steps:Vec<CheatSheetStep>,#[serde(default)]template_variables:Vec<TemplateVariable>}
#[derive(Serialize,Deserialize)] #[serde(rename_all="camelCase")] struct Backup{version:u8,exported_at:String,categories:Vec<BackupCategory>,cheatsheets:Vec<BackupItem>}

fn default_sheet_type()->String{"single".into()} fn now()->String{chrono::Utc::now().to_rfc3339()} fn map_err<E:std::fmt::Display>(e:E)->String{e.to_string()}
fn migrate_command_sets(conn:&Connection)->Result<(),rusqlite::Error>{let names=conn.prepare("PRAGMA table_info(cheatsheets)")?.query_map([],|r|r.get::<_,String>(1))?.collect::<Result<Vec<_>,_>>()?;if !names.iter().any(|n|n=="type"){conn.execute("ALTER TABLE cheatsheets ADD COLUMN type TEXT NOT NULL DEFAULT 'single' CHECK(type IN ('single','command_set'))",[])?;}conn.execute_batch(include_str!("../migrations/003_command_sets.sql"))}
fn get_sheet(conn:&Connection,id:i64)->Result<CheatSheet,String>{let mut q=conn.prepare("SELECT c.id,c.category_id,k.name,c.title,c.description,c.type,c.content,c.created_at,c.updated_at FROM cheatsheets c JOIN categories k ON k.id=c.category_id WHERE c.id=?1").map_err(map_err)?;let mut s=q.query_row([id],|r|Ok(CheatSheet{id:r.get(0)?,category_id:r.get(1)?,category_name:r.get(2)?,title:r.get(3)?,description:r.get(4)?,sheet_type:r.get(5)?,content:r.get(6)?,steps:vec![],tags:vec![],template_variables:vec![],created_at:r.get(7)?,updated_at:r.get(8)?})).map_err(map_err)?;let mut q=conn.prepare("SELECT t.name FROM tags t JOIN cheatsheet_tags ct ON ct.tag_id=t.id WHERE ct.cheatsheet_id=?1 ORDER BY t.name").map_err(map_err)?;s.tags=q.query_map([id],|r|r.get(0)).map_err(map_err)?.collect::<Result<_,_>>().map_err(map_err)?;let mut q=conn.prepare("SELECT id,name,default_value,description,sort_order FROM template_variables WHERE cheatsheet_id=?1 ORDER BY sort_order,id").map_err(map_err)?;s.template_variables=q.query_map([id],|r|Ok(TemplateVariable{id:Some(r.get(0)?),name:r.get(1)?,default_value:r.get(2)?,description:r.get(3)?,sort_order:r.get(4)?})).map_err(map_err)?.collect::<Result<_,_>>().map_err(map_err)?;let mut q=conn.prepare("SELECT id,cheatsheet_id,sort_order,title,description,content FROM cheatsheet_steps WHERE cheatsheet_id=?1 ORDER BY sort_order,id").map_err(map_err)?;s.steps=q.query_map([id],|r|Ok(CheatSheetStep{id:Some(r.get(0)?),cheatsheet_id:Some(r.get(1)?),sort_order:r.get(2)?,title:r.get(3)?,description:r.get(4)?,content:r.get(5)?})).map_err(map_err)?.collect::<Result<_,_>>().map_err(map_err)?;Ok(s)}

#[tauri::command] fn list_categories(state:State<AppState>)->Result<Vec<Category>,String>{let c=state.0.lock().map_err(map_err)?;let mut q=c.prepare("SELECT id,name,sort_order,created_at FROM categories ORDER BY sort_order,name").map_err(map_err)?;let rows=q.query_map([],|r|Ok(Category{id:r.get(0)?,name:r.get(1)?,sort_order:r.get(2)?,created_at:r.get(3)?})).map_err(map_err)?.collect::<Result<_,_>>().map_err(map_err);rows}
#[tauri::command] fn create_category(state:State<AppState>,name:String)->Result<Category,String>{let c=state.0.lock().map_err(map_err)?;if name.trim().is_empty(){return Err("カテゴリ名を入力してください".into())}let order=c.query_row("SELECT COALESCE(MAX(sort_order),-1)+1 FROM categories",[],|r|r.get(0)).map_err(map_err)?;let created=now();c.execute("INSERT INTO categories(name,sort_order,created_at)VALUES(?1,?2,?3)",params![name.trim(),order,created]).map_err(map_err)?;Ok(Category{id:c.last_insert_rowid(),name:name.trim().into(),sort_order:order,created_at:created})}
#[tauri::command] fn delete_category(state:State<AppState>,id:i64)->Result<(),String>{let c=state.0.lock().map_err(map_err)?;if c.query_row("SELECT COUNT(*) FROM cheatsheets WHERE category_id=?1",[id],|r|r.get::<_,i64>(0)).map_err(map_err)?>0{return Err("このカテゴリにはCheatSheetがあるため削除できません".into())}c.execute("DELETE FROM categories WHERE id=?1",[id]).map_err(map_err)?;Ok(())}
#[tauri::command] fn list_cheatsheets(state:State<AppState>,query:String,category_id:Option<i64>)->Result<Vec<CheatSheet>,String>{let c=state.0.lock().map_err(map_err)?;let needle=format!("%{}%",query.trim());let mut q=c.prepare("SELECT DISTINCT c.id FROM cheatsheets c JOIN categories k ON k.id=c.category_id LEFT JOIN cheatsheet_tags ct ON ct.cheatsheet_id=c.id LEFT JOIN tags t ON t.id=ct.tag_id LEFT JOIN cheatsheet_steps s ON s.cheatsheet_id=c.id WHERE (?1 IS NULL OR c.category_id=?1) AND (?2='' OR c.title LIKE ?3 OR c.description LIKE ?3 OR c.content LIKE ?3 OR k.name LIKE ?3 OR t.name LIKE ?3 OR s.title LIKE ?3 OR s.description LIKE ?3 OR s.content LIKE ?3) ORDER BY c.updated_at DESC").map_err(map_err)?;let ids=q.query_map(params![category_id,query.trim(),needle],|r|r.get(0)).map_err(map_err)?.collect::<Result<Vec<i64>,_>>().map_err(map_err)?;ids.into_iter().map(|id|get_sheet(&c,id)).collect()}

#[tauri::command] fn save_cheatsheet(state:State<AppState>,input:CheatSheetInput)->Result<CheatSheet,String>{let is_set=input.sheet_type=="command_set";if input.title.trim().is_empty()||(!is_set&&input.content.trim().is_empty())||(is_set&&(input.steps.is_empty()||input.steps.iter().any(|s|s.content.trim().is_empty()))){return Err("タイトルとコマンド本文は必須です".into())}if input.sheet_type!="single"&&!is_set{return Err("CheatSheetの種類が不正です".into())}let mut c=state.0.lock().map_err(map_err)?;let tx=c.transaction().map_err(map_err)?;let timestamp=now();let id=if let Some(id)=input.id{tx.execute("UPDATE cheatsheets SET category_id=?1,title=?2,description=?3,type=?4,content=?5,updated_at=?6 WHERE id=?7",params![input.category_id,input.title.trim(),input.description.trim(),input.sheet_type,input.content,timestamp,id]).map_err(map_err)?;for table in ["cheatsheet_tags","template_variables","cheatsheet_steps"]{tx.execute(&format!("DELETE FROM {table} WHERE cheatsheet_id=?1"),[id]).map_err(map_err)?;}id}else{tx.execute("INSERT INTO cheatsheets(category_id,title,description,type,content,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?6)",params![input.category_id,input.title.trim(),input.description.trim(),input.sheet_type,input.content,timestamp]).map_err(map_err)?;tx.last_insert_rowid()};for tag in input.tags.iter().map(|t|t.trim()).filter(|t|!t.is_empty()){tx.execute("INSERT OR IGNORE INTO tags(name)VALUES(?1)",[tag]).map_err(map_err)?;let tag_id:i64=tx.query_row("SELECT id FROM tags WHERE name=?1 COLLATE NOCASE",[tag],|r|r.get(0)).map_err(map_err)?;tx.execute("INSERT OR IGNORE INTO cheatsheet_tags VALUES(?1,?2)",params![id,tag_id]).map_err(map_err)?;}for v in input.template_variables{tx.execute("INSERT INTO template_variables(cheatsheet_id,name,default_value,description,sort_order,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?6)",params![id,v.name,v.default_value,v.description,v.sort_order,timestamp]).map_err(map_err)?;}if is_set{for (order,s) in input.steps.into_iter().enumerate(){tx.execute("INSERT INTO cheatsheet_steps(cheatsheet_id,sort_order,title,description,content,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?6)",params![id,order as i64,s.title.trim(),s.description.trim(),s.content,timestamp]).map_err(map_err)?;}}tx.commit().map_err(map_err)?;get_sheet(&c,id)}
#[tauri::command] fn delete_cheatsheet(state:State<AppState>,id:i64)->Result<(),String>{let c=state.0.lock().map_err(map_err)?;c.execute("DELETE FROM cheatsheets WHERE id=?1",[id]).map_err(map_err)?;c.execute("DELETE FROM tags WHERE id NOT IN(SELECT tag_id FROM cheatsheet_tags)",[]).map_err(map_err)?;Ok(())}
#[tauri::command] fn delete_cheatsheets(state:State<AppState>,ids:Vec<i64>)->Result<usize,String>{let mut c=state.0.lock().map_err(map_err)?;let tx=c.transaction().map_err(map_err)?;let mut n=0;for id in ids{n+=tx.execute("DELETE FROM cheatsheets WHERE id=?1",[id]).map_err(map_err)?;}tx.execute("DELETE FROM tags WHERE id NOT IN(SELECT tag_id FROM cheatsheet_tags)",[]).map_err(map_err)?;tx.commit().map_err(map_err)?;Ok(n)}

#[tauri::command] fn export_json(state:State<AppState>,path:String)->Result<(),String>{let c=state.0.lock().map_err(map_err)?;let categories={let mut q=c.prepare("SELECT name,sort_order FROM categories ORDER BY sort_order,name").map_err(map_err)?;let rows=q.query_map([],|r|Ok(BackupCategory{name:r.get(0)?,sort_order:r.get(1)?})).map_err(map_err)?.collect::<Result<Vec<_>,_>>().map_err(map_err)?;rows};let ids={let mut q=c.prepare("SELECT id FROM cheatsheets ORDER BY updated_at").map_err(map_err)?;let rows=q.query_map([],|r|r.get(0)).map_err(map_err)?.collect::<Result<Vec<i64>,_>>().map_err(map_err)?;rows};let cheatsheets=ids.into_iter().map(|id|get_sheet(&c,id)).collect::<Result<Vec<_>,_>>()?.into_iter().map(|s|BackupItem{category:s.category_name,title:s.title,description:s.description,sheet_type:s.sheet_type,content:s.content,tags:s.tags,steps:s.steps,template_variables:s.template_variables}).collect();let backup=Backup{version:2,exported_at:now(),categories,cheatsheets};fs::write(path,serde_json::to_string_pretty(&backup).map_err(map_err)?).map_err(map_err)}
#[tauri::command] fn import_json(state:State<AppState>,path:String)->Result<(),String>{let raw=fs::read_to_string(path).map_err(map_err)?;let backup:Backup=serde_json::from_str(&raw).map_err(|e|format!("JSON形式が不正です: {e}"))?;if backup.version!=1&&backup.version!=2{return Err("未対応のバックアップバージョンです".into())}let mut c=state.0.lock().map_err(map_err)?;let tx=c.transaction().map_err(map_err)?;for cat in backup.categories{tx.execute("INSERT OR IGNORE INTO categories(name,sort_order,created_at)VALUES(?1,?2,?3)",params![cat.name,cat.sort_order,now()]).map_err(map_err)?;}for item in backup.cheatsheets{let category_id:i64=tx.query_row("SELECT id FROM categories WHERE name=?1 COLLATE NOCASE",[item.category],|r|r.get(0)).map_err(map_err)?;let timestamp=now();let kind=if item.sheet_type=="command_set"{"command_set"}else{"single"};tx.execute("INSERT INTO cheatsheets(category_id,title,description,type,content,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?6)",params![category_id,item.title,item.description,kind,item.content,timestamp]).map_err(map_err)?;let id=tx.last_insert_rowid();for tag in item.tags{tx.execute("INSERT OR IGNORE INTO tags(name)VALUES(?1)",[&tag]).map_err(map_err)?;let tag_id:i64=tx.query_row("SELECT id FROM tags WHERE name=?1 COLLATE NOCASE",[tag],|r|r.get(0)).map_err(map_err)?;tx.execute("INSERT OR IGNORE INTO cheatsheet_tags VALUES(?1,?2)",params![id,tag_id]).map_err(map_err)?;}for v in item.template_variables{tx.execute("INSERT INTO template_variables(cheatsheet_id,name,default_value,description,sort_order,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?6)",params![id,v.name,v.default_value,v.description,v.sort_order,timestamp]).map_err(map_err)?;}for (order,s) in item.steps.into_iter().enumerate(){tx.execute("INSERT INTO cheatsheet_steps(cheatsheet_id,sort_order,title,description,content,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?6)",params![id,order as i64,s.title,s.description,s.content,timestamp]).map_err(map_err)?;}}tx.commit().map_err(map_err)}

pub fn run(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).setup(|app|{let dir=app.path().app_data_dir()?;fs::create_dir_all(&dir)?;let conn=Connection::open(PathBuf::from(dir).join("cheatsheet.db"))?;conn.execute_batch(include_str!("../migrations/001_initial.sql"))?;conn.execute_batch(include_str!("../migrations/002_template_variables.sql"))?;migrate_command_sets(&conn)?;for(i,name)in["Git","PowerShell","Xcode","Supabase","Vercel","OpenShift","Linux"].iter().enumerate(){conn.execute("INSERT OR IGNORE INTO categories(name,sort_order,created_at)VALUES(?1,?2,?3)",params![name,i as i64,now()])?;}app.manage(AppState(Mutex::new(conn)));Ok(())}).invoke_handler(tauri::generate_handler![list_categories,create_category,delete_category,list_cheatsheets,save_cheatsheet,delete_cheatsheet,delete_cheatsheets,export_json,import_json]).run(tauri::generate_context!()).expect("error while running CheatSheet");}

#[cfg(test)] mod tests{use super::*;#[test]fn migration_is_idempotent_and_preserves_old_rows(){let c=Connection::open_in_memory().unwrap();c.execute_batch(include_str!("../migrations/001_initial.sql")).unwrap();c.execute("INSERT INTO categories(name,sort_order,created_at)VALUES('Git',0,'now')",[]).unwrap();c.execute("INSERT INTO cheatsheets(category_id,title,description,content,created_at,updated_at)VALUES(1,'Status','','git status','now','now')",[]).unwrap();migrate_command_sets(&c).unwrap();migrate_command_sets(&c).unwrap();let kind:String=c.query_row("SELECT type FROM cheatsheets",[],|r|r.get(0)).unwrap();assert_eq!(kind,"single");}#[test]fn version_one_backup_defaults_to_single_command(){let raw=r#"{"version":1,"exportedAt":"now","categories":[],"cheatsheets":[{"category":"Git","title":"Status","description":"","content":"git status","tags":[],"templateVariables":[]}]}"#;let backup:Backup=serde_json::from_str(raw).unwrap();assert_eq!(backup.cheatsheets[0].sheet_type,"single");assert!(backup.cheatsheets[0].steps.is_empty());}}
