use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use std::{fs, path::PathBuf, sync::Mutex};
use tauri::{Manager, State};

struct AppState(Mutex<Connection>);
#[derive(Serialize, Deserialize, Clone)] #[serde(rename_all = "camelCase")] struct Category { id: i64, name: String, sort_order: i64, created_at: String }
#[derive(Serialize, Deserialize, Clone)] #[serde(rename_all = "camelCase")] struct CheatSheet { id: i64, category_id: i64, category_name: String, title: String, description: String, content: String, tags: Vec<String>, created_at: String, updated_at: String }
#[derive(Deserialize)] #[serde(rename_all = "camelCase")] struct CheatSheetInput { id: Option<i64>, category_id: i64, title: String, description: String, content: String, tags: Vec<String> }
#[derive(Serialize, Deserialize)] #[serde(rename_all = "camelCase")] struct BackupCategory { name: String, sort_order: i64 }
#[derive(Serialize, Deserialize)] #[serde(rename_all = "camelCase")] struct BackupItem { category: String, title: String, description: String, content: String, tags: Vec<String> }
#[derive(Serialize, Deserialize)] #[serde(rename_all = "camelCase")] struct Backup { version: u8, exported_at: String, categories: Vec<BackupCategory>, cheatsheets: Vec<BackupItem> }

fn now() -> String { chrono::Utc::now().to_rfc3339() }
fn map_err<E: std::fmt::Display>(e: E) -> String { e.to_string() }
fn get_sheet(conn: &Connection, id: i64) -> Result<CheatSheet, String> {
  let mut stmt = conn.prepare("SELECT c.id,c.category_id,k.name,c.title,c.description,c.content,c.created_at,c.updated_at FROM cheatsheets c JOIN categories k ON k.id=c.category_id WHERE c.id=?1").map_err(map_err)?;
  let mut sheet = stmt.query_row([id], |r| Ok(CheatSheet { id:r.get(0)?,category_id:r.get(1)?,category_name:r.get(2)?,title:r.get(3)?,description:r.get(4)?,content:r.get(5)?,tags:vec![],created_at:r.get(6)?,updated_at:r.get(7)? })).map_err(map_err)?;
  let mut tags = conn.prepare("SELECT t.name FROM tags t JOIN cheatsheet_tags ct ON ct.tag_id=t.id WHERE ct.cheatsheet_id=?1 ORDER BY t.name").map_err(map_err)?;
  sheet.tags = tags.query_map([id], |r| r.get(0)).map_err(map_err)?.collect::<Result<_,_>>().map_err(map_err)?; Ok(sheet)
}
#[tauri::command] fn list_categories(state: State<AppState>) -> Result<Vec<Category>,String> { let conn=state.0.lock().map_err(map_err)?; let mut s=conn.prepare("SELECT id,name,sort_order,created_at FROM categories ORDER BY sort_order,name").map_err(map_err)?; let rows=s.query_map([],|r|Ok(Category{id:r.get(0)?,name:r.get(1)?,sort_order:r.get(2)?,created_at:r.get(3)?})).map_err(map_err)?.collect::<Result<_,_>>().map_err(map_err); rows }
#[tauri::command] fn create_category(state: State<AppState>, name:String)->Result<Category,String>{let conn=state.0.lock().map_err(map_err)?; if name.trim().is_empty(){return Err("カテゴリ名を入力してください".into())} let order:i64=conn.query_row("SELECT COALESCE(MAX(sort_order),-1)+1 FROM categories",[],|r|r.get(0)).map_err(map_err)?; let created=now(); conn.execute("INSERT INTO categories(name,sort_order,created_at) VALUES(?1,?2,?3)",params![name.trim(),order,created]).map_err(map_err)?; Ok(Category{id:conn.last_insert_rowid(),name:name.trim().into(),sort_order:order,created_at:created})}
#[tauri::command] fn delete_category(state:State<AppState>,id:i64)->Result<(),String>{let conn=state.0.lock().map_err(map_err)?; let count:i64=conn.query_row("SELECT COUNT(*) FROM cheatsheets WHERE category_id=?1",[id],|r|r.get(0)).map_err(map_err)?; if count>0{return Err("このカテゴリにはCheatSheetがあるため削除できません".into())} conn.execute("DELETE FROM categories WHERE id=?1",[id]).map_err(map_err)?;Ok(())}
#[tauri::command] fn list_cheatsheets(state:State<AppState>,query:String,category_id:Option<i64>)->Result<Vec<CheatSheet>,String>{let conn=state.0.lock().map_err(map_err)?; let needle=format!("%{}%",query.trim()); let mut stmt=conn.prepare("SELECT DISTINCT c.id FROM cheatsheets c JOIN categories k ON k.id=c.category_id LEFT JOIN cheatsheet_tags ct ON ct.cheatsheet_id=c.id LEFT JOIN tags t ON t.id=ct.tag_id WHERE (?1 IS NULL OR c.category_id=?1) AND (?2='' OR c.title LIKE ?3 OR c.description LIKE ?3 OR c.content LIKE ?3 OR k.name LIKE ?3 OR t.name LIKE ?3) ORDER BY c.updated_at DESC").map_err(map_err)?; let ids:Vec<i64>=stmt.query_map(params![category_id,query.trim(),needle],|r|r.get(0)).map_err(map_err)?.collect::<Result<_,_>>().map_err(map_err)?; ids.into_iter().map(|id|get_sheet(&conn,id)).collect()}
#[tauri::command] fn save_cheatsheet(state:State<AppState>,input:CheatSheetInput)->Result<CheatSheet,String>{if input.title.trim().is_empty()||input.content.trim().is_empty(){return Err("タイトルと本文は必須です".into())} let mut conn=state.0.lock().map_err(map_err)?; let tx=conn.transaction().map_err(map_err)?; let timestamp=now(); let id=if let Some(id)=input.id{tx.execute("UPDATE cheatsheets SET category_id=?1,title=?2,description=?3,content=?4,updated_at=?5 WHERE id=?6",params![input.category_id,input.title.trim(),input.description.trim(),input.content,timestamp,id]).map_err(map_err)?;tx.execute("DELETE FROM cheatsheet_tags WHERE cheatsheet_id=?1",[id]).map_err(map_err)?;id}else{tx.execute("INSERT INTO cheatsheets(category_id,title,description,content,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?5)",params![input.category_id,input.title.trim(),input.description.trim(),input.content,timestamp]).map_err(map_err)?;tx.last_insert_rowid()}; for tag in input.tags.iter().map(|t|t.trim()).filter(|t|!t.is_empty()){tx.execute("INSERT OR IGNORE INTO tags(name)VALUES(?1)",[tag]).map_err(map_err)?;let tag_id:i64=tx.query_row("SELECT id FROM tags WHERE name=?1 COLLATE NOCASE",[tag],|r|r.get(0)).map_err(map_err)?;tx.execute("INSERT OR IGNORE INTO cheatsheet_tags VALUES(?1,?2)",params![id,tag_id]).map_err(map_err)?;} tx.commit().map_err(map_err)?;get_sheet(&conn,id)}
#[tauri::command] fn delete_cheatsheet(state:State<AppState>,id:i64)->Result<(),String>{let conn=state.0.lock().map_err(map_err)?;conn.execute("DELETE FROM cheatsheets WHERE id=?1",[id]).map_err(map_err)?;conn.execute("DELETE FROM tags WHERE id NOT IN(SELECT tag_id FROM cheatsheet_tags)",[]).map_err(map_err)?;Ok(())}
#[tauri::command] fn export_json(state:State<AppState>,path:String)->Result<(),String>{let conn=state.0.lock().map_err(map_err)?;let categories={let mut s=conn.prepare("SELECT name,sort_order FROM categories ORDER BY sort_order,name").map_err(map_err)?;let rows=s.query_map([],|r|Ok(BackupCategory{name:r.get(0)?,sort_order:r.get(1)?})).map_err(map_err)?.collect::<Result<Vec<_>,_>>().map_err(map_err)?;rows};let ids={let mut s=conn.prepare("SELECT id FROM cheatsheets ORDER BY updated_at").map_err(map_err)?;let rows=s.query_map([],|r|r.get(0)).map_err(map_err)?.collect::<Result<Vec<i64>,_>>().map_err(map_err)?;rows};let cheatsheets=ids.into_iter().map(|id|get_sheet(&conn,id)).collect::<Result<Vec<_>,_>>()?.into_iter().map(|s|BackupItem{category:s.category_name,title:s.title,description:s.description,content:s.content,tags:s.tags}).collect();let backup=Backup{version:1,exported_at:now(),categories,cheatsheets};fs::write(path,serde_json::to_string_pretty(&backup).map_err(map_err)?).map_err(map_err)}
#[tauri::command] fn import_json(state:State<AppState>,path:String)->Result<(),String>{let raw=fs::read_to_string(path).map_err(map_err)?;let backup:Backup=serde_json::from_str(&raw).map_err(|e|format!("JSON形式が不正です: {e}"))?;if backup.version!=1{return Err("未対応のバックアップバージョンです".into())}let mut conn=state.0.lock().map_err(map_err)?;let tx=conn.transaction().map_err(map_err)?;for c in backup.categories{tx.execute("INSERT OR IGNORE INTO categories(name,sort_order,created_at)VALUES(?1,?2,?3)",params![c.name,c.sort_order,now()]).map_err(map_err)?;}for item in backup.cheatsheets{let category_id:i64=tx.query_row("SELECT id FROM categories WHERE name=?1 COLLATE NOCASE",[item.category],|r|r.get(0)).map_err(map_err)?;let timestamp=now();tx.execute("INSERT INTO cheatsheets(category_id,title,description,content,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?5)",params![category_id,item.title,item.description,item.content,timestamp]).map_err(map_err)?;let id=tx.last_insert_rowid();for tag in item.tags{tx.execute("INSERT OR IGNORE INTO tags(name)VALUES(?1)",[&tag]).map_err(map_err)?;let tag_id:i64=tx.query_row("SELECT id FROM tags WHERE name=?1 COLLATE NOCASE",[tag],|r|r.get(0)).map_err(map_err)?;tx.execute("INSERT OR IGNORE INTO cheatsheet_tags VALUES(?1,?2)",params![id,tag_id]).map_err(map_err)?;}}tx.commit().map_err(map_err)}

pub fn run(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).setup(|app|{let data_dir=app.path().app_data_dir()?;fs::create_dir_all(&data_dir)?;let db_path:PathBuf=data_dir.join("cheatsheet.db");let conn=Connection::open(db_path)?;conn.execute_batch(include_str!("../migrations/001_initial.sql"))?;let defaults=["Git","PowerShell","Xcode","Supabase","Vercel","OpenShift","Linux"];for (i,name) in defaults.iter().enumerate(){conn.execute("INSERT OR IGNORE INTO categories(name,sort_order,created_at)VALUES(?1,?2,?3)",params![name,i as i64,now()])?;}app.manage(AppState(Mutex::new(conn)));Ok(())}).invoke_handler(tauri::generate_handler![list_categories,create_category,delete_category,list_cheatsheets,save_cheatsheet,delete_cheatsheet,export_json,import_json]).run(tauri::generate_context!()).expect("error while running CheatSheet");}
